update

diff --git a/.github/workflows/verce-deploy-dev.yml b/.github/workflows/verce-deploy-dev.yml
--- a/.github/workflows/verce-deploy-dev.yml
+++ b/.github/workflows/verce-deploy-dev.yml
@@ -11,4 +11,8 @@ jobs:
     steps:
       - name: Trigger Vercel Deploy Hook
         run: |
-          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
+          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
+            echo "Error: VERCEL_DEPLOY_HOOK secret is not set."
+            exit 1
+          fi
+          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
